using System.Text.Json;
using System.Text.Json.Serialization;

namespace Baton.Domain;

/// <summary>
/// Serializes a string-backed strongly-typed ID as a plain JSON string (both as a value and as a
/// dictionary key), rather than as a wrapper object with a "Value" property.
/// </summary>
public abstract class StringIdJsonConverter<T> : JsonConverter<T>
{
    protected abstract T Create(string value);

    protected abstract string GetValue(T id);

    public override T Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        => Create(reader.GetString() ?? throw new JsonException($"Expected a string for {typeToConvert}."));

    public override void Write(Utf8JsonWriter writer, T value, JsonSerializerOptions options)
        => writer.WriteStringValue(GetValue(value));

    public override T ReadAsPropertyName(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        => Create(reader.GetString() ?? throw new JsonException($"Expected a string property name for {typeToConvert}."));

    public override void WriteAsPropertyName(Utf8JsonWriter writer, T value, JsonSerializerOptions options)
        => writer.WritePropertyName(GetValue(value));
}

/// <summary>
/// Globally unique, generated once by Flow. The sole join key between Flow-owned and
/// Core-owned events for a given execution — never associated by timestamp or file order.
/// </summary>
[JsonConverter(typeof(Converter))]
public readonly record struct ExecutionId(string Value)
{
    public override string ToString() => Value;

    private sealed class Converter : StringIdJsonConverter<ExecutionId>
    {
        protected override ExecutionId Create(string value) => new(value);
        protected override string GetValue(ExecutionId id) => id.Value;
    }
}

/// <summary>
/// Stable identity for one fleet-level attempt, generated by the Baton producer before it launches
/// work and retained independently of the room and execution ids that may become known later.
/// </summary>
[JsonConverter(typeof(Converter))]
public readonly record struct FleetAttemptId(string Value)
{
    public static FleetAttemptId New() => new(Guid.NewGuid().ToString("N"));

    public override string ToString() => Value;

    private sealed class Converter : StringIdJsonConverter<FleetAttemptId>
    {
        protected override FleetAttemptId Create(string value) => new(value);
        protected override string GetValue(FleetAttemptId id) => id.Value;
    }
}

/// <summary>Identifies the workflow task an <see cref="ExecutionRequest"/> belongs to.</summary>
[JsonConverter(typeof(Converter))]
public readonly record struct WorkflowId(string Value)
{
    public override string ToString() => Value;

    private sealed class Converter : StringIdJsonConverter<WorkflowId>
    {
        protected override WorkflowId Create(string value) => new(value);
        protected override string GetValue(WorkflowId id) => id.Value;
    }
}

/// <summary>
/// Identifies a step within a <see cref="WorkflowDefinition"/>. <c>DependsOn</c> references
/// <see cref="StepId"/>, never <see cref="ExecutionId"/>.
/// </summary>
[JsonConverter(typeof(Converter))]
public readonly record struct StepId(string Value)
{
    public override string ToString() => Value;

    private sealed class Converter : StringIdJsonConverter<StepId>
    {
        protected override StepId Create(string value) => new(value);
        protected override string GetValue(StepId id) => id.Value;
    }
}

/// <summary>Identifies a <see cref="WorkflowDefinition"/> template, stable across versions.</summary>
[JsonConverter(typeof(Converter))]
public readonly record struct WorkflowTemplateId(string Value)
{
    public override string ToString() => Value;

    private sealed class Converter : StringIdJsonConverter<WorkflowTemplateId>
    {
        protected override WorkflowTemplateId Create(string value) => new(value);
        protected override string GetValue(WorkflowTemplateId id) => id.Value;
    }
}

/// <summary>Globally unique, generated once by Flow when a template is bound to a task.</summary>
[JsonConverter(typeof(Converter))]
public readonly record struct WorkflowDefinitionSnapshotId(string Value)
{
    public override string ToString() => Value;

    private sealed class Converter : StringIdJsonConverter<WorkflowDefinitionSnapshotId>
    {
        protected override WorkflowDefinitionSnapshotId Create(string value) => new(value);
        protected override string GetValue(WorkflowDefinitionSnapshotId id) => id.Value;
    }
}

/// <summary>Identifies an <see cref="FlowEvent.ExternalDecisionRecorded"/> event (spec/baton.md §5).</summary>
[JsonConverter(typeof(Converter))]
public readonly record struct DecisionId(string Value)
{
    public override string ToString() => Value;

    private sealed class Converter : StringIdJsonConverter<DecisionId>
    {
        protected override DecisionId Create(string value) => new(value);
        protected override string GetValue(DecisionId id) => id.Value;
    }
}

/// <summary>Identifies a held-work reference (workflow directory path or reference id).</summary>
[JsonConverter(typeof(Converter))]
public readonly record struct HeldWorkRef(string Value)
{
    public string AsWorkflowDirectoryPath() => Value;
    public override string ToString() => Value;

    private sealed class Converter : StringIdJsonConverter<HeldWorkRef>
    {
        protected override HeldWorkRef Create(string value) => new(value);
        protected override string GetValue(HeldWorkRef id) => id.Value;
    }
}

/// <summary>Identifies a grant issued to a worker.</summary>
[JsonConverter(typeof(Converter))]
public readonly record struct GrantId(string Value)
{
    public override string ToString() => Value;

    private sealed class Converter : StringIdJsonConverter<GrantId>
    {
        protected override GrantId Create(string value) => new(value);
        protected override string GetValue(GrantId id) => id.Value;
    }
}

/// <summary>Identifies a worker instance.</summary>
[JsonConverter(typeof(Converter))]
public readonly record struct WorkerId(string Value)
{
    public override string ToString() => Value;

    private sealed class Converter : StringIdJsonConverter<WorkerId>
    {
        protected override WorkerId Create(string value) => new(value);
        protected override string GetValue(WorkerId id) => id.Value;
    }
}


