namespace Baton.Cli;

/// <summary>
/// Parses <c>baton memory retract</c> (#2113). Same shape as <see cref="MemoryAddOptionsParser"/> —
/// one <see cref="CliArgumentException"/> per malformed invocation, never a bare
/// <see cref="InvalidOperationException"/>.
/// </summary>
public static class MemoryRetractOptionsParser
{
    public const string Usage =
        "Usage: baton memory retract <entry-id> --reason <text> [--repository <id>] [--help]";

    /// <summary>
    /// What <c>--help</c> prints under <see cref="Usage"/>. Each line states a negative a reader's
    /// prior would otherwise fill in wrongly: that nothing is deleted, that the projections are NOT
    /// regenerated by it, and that there is no un-retract.
    /// </summary>
    public static IReadOnlyList<string> HelpLines { get; } =
    [
        "",
        "Retracts ONE entry in Baton's canonical store: appends a retraction row naming it, with your",
        "reason, to ~/.baton/<repo-slug>/memory/retractions.jsonl. From then on the entry is absent from",
        "every resolved read of the store and from every projection 'baton memory sync' writes.",
        "",
        "NOTHING IS DELETED. The entry's row stays in entries.jsonl byte-for-byte, and the retraction",
        "sits beside it as its own row -- history is never deleted (spec/baton.md §12). 'baton memory",
        "audit' lists every retraction with its reason. This is the difference from 'baton memory import",
        "--undo', which removes a row that should never have been written; a retraction says the row was",
        "right and is not any more.",
        "",
        "  <entry-id>          The id of the entry, as 'baton memory add' or 'baton memory sync' printed",
        "                      it. Case does not matter; the store's own spelling is recorded.",
        "  --reason <text>     Required and non-blank. Stored verbatim; nothing here or downstream parses",
        "                      it for meaning. A retraction with no reason would read as a deletion.",
        "  --repository <id>   The subject, e.g. 'github.com/owner/repo'. Default: the repository git",
        "                      answers for in the current directory; if git answers for nothing and you",
        "                      passed no id, this refuses rather than guessing which store to look in.",
        "",
        "AN ID THAT NAMES NO ENTRY IN THAT STORE IS REFUSED, with exit code 1 and nothing written. So is",
        "an entry that is ALREADY RETRACTED: the earlier retraction, its reason and its author are printed",
        "instead, because a second row would append nothing and a run that reported success having",
        "written nothing is the failure this refusal removes.",
        "",
        "THERE IS NO UN-RETRACT. A retraction that turns out to be wrong is answered by 'baton memory add'",
        "of the fact as it now stands, which leaves the mistaken retraction readable as history.",
        "",
        "EVERY RETRACTION RECORDS WHO MADE IT ('retractedBy'), read the same way 'baton memory add' reads",
        "'assertedBy': 'operator' outside a lane, '<role>/<vendor>/<room>' inside one. A reading of the",
        "environment, not a credential.",
        "",
        "A SUCCESSFUL RETRACTION RUNS THE SAME IDEMPOTENT PROJECTION AS 'baton memory sync --apply'. If",
        "projection fails, the retraction remains committed and sync-pending.json records a durable",
        "daemon retry. Projection completion does not prove that a vendor loaded or consumed the cache.",
    ];

    public static MemoryRetractOptions Parse(IReadOnlyList<string> args)
    {
        ArgumentNullException.ThrowIfNull(args);

        string? entryId = null;
        string? reason = null;
        string? repository = null;
        var help = false;

        var i = 0;
        while (i < args.Count)
        {
            var arg = args[i];
            switch (arg)
            {
                case "--help":
                case "-h":
                    help = true;
                    i++;
                    break;
                case "--reason":
                    reason = RequireValue(args, i);
                    i += 2;
                    break;
                case "--repository":
                    repository = MemoryAddOptionsParser.ParseRepository(RequireValue(args, i), Usage);
                    i += 2;
                    break;
                default:
                    if (arg.StartsWith("--", StringComparison.Ordinal))
                    {
                        throw new CliArgumentException($"Unknown option '{arg}'. {Usage}");
                    }

                    if (entryId is not null)
                    {
                        throw new CliArgumentException(
                            $"Unexpected argument '{arg}': this verb retracts ONE entry per call, and " +
                            $"'{entryId}' was already given. {Usage}");
                    }

                    entryId = arg;
                    i++;
                    break;
            }
        }

        if (help)
        {
            // Help is answered before the invocation is adjudicated, the same posture
            // MemoryAddOptionsParser takes: '--help' asks what the verb is, not whether this call is
            // well formed.
            return new MemoryRetractOptions(string.Empty, string.Empty, repository, Help: true);
        }

        if (string.IsNullOrWhiteSpace(entryId))
        {
            throw new CliArgumentException(
                $"An <entry-id> is required: this verb retracts one entry per call and none was named. {Usage}",
                "pass the entry's id, as 'baton memory add' printed it -- for example: " +
                "baton memory retract 0123456789abcdef0123456789abcdef --reason \"no longer true\".");
        }

        if (string.IsNullOrWhiteSpace(reason))
        {
            throw new CliArgumentException(
                $"'--reason' is required and cannot be blank: a retraction with no reason is " +
                $"indistinguishable from a deletion, and this verb deletes nothing. {Usage}",
                "say why the entry no longer holds, for example: --reason \"the smoke tasks moved into Baton.slnx\".");
        }

        return new MemoryRetractOptions(entryId.Trim(), reason, repository, Help: false);
    }

    private static string RequireValue(IReadOnlyList<string> args, int index)
    {
        if (index + 1 >= args.Count)
        {
            throw new CliArgumentException(
                $"Option '{args[index]}' requires a value. {Usage}",
                $"pass a value after '{args[index]}'.");
        }

        return args[index + 1];
    }
}
