using Baton.Accounting;
using Baton.Memory;

namespace Baton.Cli;

/// <summary>
/// Parses <c>baton memory add</c> (#2071, slice one of #1852's write path). Same shape as
/// <see cref="MemoryImportOptionsParser"/> — one <see cref="CliArgumentException"/> per malformed
/// invocation, never a bare <see cref="InvalidOperationException"/>.
/// </summary>
public static class MemoryAddOptionsParser
{
    public const string Usage =
        "Usage: baton memory add --text <text> --kind <kind> [--repository <id>|fleet] [--dry-run] [--help]";

    /// <summary>
    /// The kinds this verb accepts, in the spelling the store writes — derived from
    /// <see cref="MemoryKind"/> itself rather than typed out again, so a new member cannot be accepted
    /// here under a name the JSON never uses.
    /// </summary>
    /// <remarks>
    /// <b><see cref="MemoryKind.Unknown"/> is excluded, and that is a refusal rather than an omission.</b>
    /// That member is the ABSENCE of a kind, recorded when nothing available could establish one; a
    /// caller of <c>add</c> is the writer and has one, so accepting the word would let a declaration be
    /// spelled as its own absence. It is also why <c>--kind</c> has no default:
    /// <see cref="MemoryKind.DurableFact"/> would mint an undeclared kind and
    /// <see cref="MemoryKind.Unknown"/> would discard one that was available for the asking.
    /// </remarks>
    public static IReadOnlyList<string> Kinds { get; } =
        [.. Enum.GetValues<MemoryKind>().Where(k => k != MemoryKind.Unknown).Select(MemoryJsonNames.Of)];

    /// <summary>
    /// What <c>--help</c> prints under <see cref="Usage"/>. Each line states a negative a reader's
    /// prior would otherwise fill in wrongly: what this writes and what it provably does not, that the
    /// projections are NOT regenerated by it, and what <c>assertedBy</c> is and is not evidence of.
    /// </summary>
    public static IReadOnlyList<string> HelpLines { get; } =
    [
        "",
        "Appends ONE memory to Baton's canonical store at ~/.baton/<repo-slug>/memory/entries.jsonl.",
        "This is the ongoing write path (#2071): the vendor memory files are PROJECTIONS of this store,",
        "regenerated by 'baton memory sync', and 'baton memory import' is a one-time backfill of what was",
        "in those files before Baton owned them.",
        "",
        "It writes in exactly two places, both under Baton's own root: the store file and one manifest,",
        "which 'baton memory import --undo <manifest>' replays to remove exactly the row this added. No",
        "vendor file is read, written, or created -- see the last paragraph.",
        "",
        "  --text <text>       The memory, stored verbatim. Nothing here or downstream parses it for",
        "                      meaning, and no kind is ever inferred from what it says.",
        $"  --kind <kind>       Required. One of: {string.Join(", ", Kinds)}.",
        "                      Recorded as DECLARED, because you are the writer. 'unknown' is not a value",
        "                      you can pass: it is the absence of a kind, which is what an IMPORTED entry",
        "                      gets when nothing established one.",
        "  --repository <id>   The subject, e.g. 'github.com/owner/repo'. Default: the repository git",
        "                      answers for in the current directory. If git answers for nothing and you",
        "                      passed no id, this refuses rather than guessing a subject -- the same",
        "                      refusal 'baton memory import' makes for a root it cannot place.",
        "  --repository fleet  The reserved FLEET store (~/.baton/fleet/memory/), for a fact that belongs",
        "                      to no repository: an operator preference, a device, a standing lane rule, a",
        "                      machine fact. Every repository's projection merges the fleet store in ahead",
        "                      of its own entries. Anything derivable from a repository is NOT fleet-scoped;",
        "                      spec/baton.md §12 states the boundary once.",
        "  --dry-run           Write NOTHING: no store row, no manifest, no directory. It still refuses a",
        "                      duplicate, so a dry run previews the run it precedes rather than a",
        "                      different one.",
        "",
        "AN ENTRY BYTE-IDENTICAL TO ONE ALREADY STORED IS REFUSED, with exit code 1 and the id of the",
        "entry it would have duplicated. The store's id is derived from the subject and the text, so",
        "'byte-identical' is the id rather than a separate comparison; the store would have skipped the",
        "append silently, and an add that reports success having written nothing is the failure this",
        "refusal removes. An edit is a NEW entry: the store is append-only and has no overwrite to offer.",
        "",
        "EVERY ENTRY RECORDS WHO ASSERTED IT ('assertedBy'). Run outside a lane that is 'operator'; run",
        "inside one it is '<role>/<vendor>/<room>', read from the lane's own environment. THAT IS A",
        "READING OF THE ENVIRONMENT, NOT A CREDENTIAL -- which roles may add and what an entry may",
        "contain is a separate, not-yet-built decision (#2071 defers it). A lane whose room or bindings",
        "cannot be read records 'lane/<room>' or 'lane/unknown', never 'operator'.",
        "",
        "THIS COMMAND DOES NOT REGENERATE THE VENDOR PROJECTIONS. It prints the exact command that does",
        "-- 'baton memory sync --repository <id> --apply' -- rather than running it, because sync writes",
        "into vendor memory roots and an add should not put bytes anywhere you did not ask it to.",
    ];

    public static MemoryAddOptions Parse(IReadOnlyList<string> args)
    {
        ArgumentNullException.ThrowIfNull(args);

        string? text = null;
        string? repository = null;
        MemoryKind? kind = null;
        var dryRun = false;
        var help = false;

        var i = 0;
        while (i < args.Count)
        {
            var arg = args[i];
            switch (arg)
            {
                case "--help":
                case "-h":
                    help = true;
                    i++;
                    break;
                case "--dry-run":
                    dryRun = true;
                    i++;
                    break;
                case "--text":
                    text = RequireValue(args, i);
                    i += 2;
                    break;
                case "--kind":
                    kind = ParseKind(RequireValue(args, i));
                    i += 2;
                    break;
                case "--repository":
                    repository = ParseRepository(RequireValue(args, i), Usage);
                    i += 2;
                    break;
                default:
                    throw new CliArgumentException(
                        arg.StartsWith("--", StringComparison.Ordinal)
                            ? $"Unknown option '{arg}'. {Usage}"
                            : $"Unexpected argument '{arg}'. {Usage}");
            }
        }

        if (help)
        {
            // Help is answered before the invocation is adjudicated, the same posture
            // MemorySyncOptionsParser takes: '--help' asks what the verb is, not whether this call is
            // well formed. The kind is a placeholder no code path reads under Help.
            return new MemoryAddOptions(string.Empty, MemoryKind.Unknown, repository, dryRun, Help: true);
        }

        if (text is not { Length: > 0 } || string.IsNullOrWhiteSpace(text))
        {
            throw new CliArgumentException(
                $"'--text' is required and cannot be blank: this verb writes one memory per call and " +
                $"there is nothing here to write. {Usage}",
                "pass the memory itself, for example: --text \"the smoke tasks live outside Baton.slnx\".");
        }

        if (kind is not { } declaredKind)
        {
            throw new CliArgumentException(
                $"'--kind' is required: an added entry's kind is DECLARED by whoever writes it, and " +
                $"nothing here will read your text to guess one. {Usage}",
                $"pass one of: {string.Join(", ", Kinds)}.");
        }

        return new MemoryAddOptions(text, declaredKind, repository, dryRun, Help: false);
    }

    /// <summary>
    /// The declared kind, matched against <see cref="Kinds"/> — the JSON spelling, so what an operator
    /// types is what the store shows.
    /// </summary>
    private static MemoryKind ParseKind(string value)
    {
        foreach (var candidate in Enum.GetValues<MemoryKind>())
        {
            if (candidate != MemoryKind.Unknown &&
                MemoryJsonNames.Of(candidate).Equals(value.Trim(), StringComparison.OrdinalIgnoreCase))
            {
                return candidate;
            }
        }

        throw new CliArgumentException(
            $"'--kind {value}' is not a kind this verb writes. {Usage}",
            value.Trim().Equals(MemoryJsonNames.Of(MemoryKind.Unknown), StringComparison.OrdinalIgnoreCase)
                ? "'unknown' is the absence of a kind, recorded for an imported entry nothing could " +
                  $"establish one for -- it is not a kind you declare. Pass one of: {string.Join(", ", Kinds)}."
                : $"pass one of: {string.Join(", ", Kinds)}.");
    }

    /// <summary>
    /// The subject, canonicalized and then held to the same standard <c>--assert</c> is
    /// (<see cref="MemoryImportOptionsParser.RequireAHostThatAProbeCouldAnswer"/>) — both are WRITE
    /// paths, and a store filed under an identity no git probe could ever answer for is one nothing
    /// will find again. <c>MemorySyncOptionsParser</c>'s own remarks are where the read path states why
    /// it applies only the first half. Shared with <c>MemoryRetractOptionsParser</c> (#2113), which
    /// names the same store file the same way; <paramref name="usage"/> is whichever verb's grammar
    /// the refusal should print.
    /// </summary>
    internal static string ParseRepository(string value, string usage)
    {
        // The reserved word is answered before canonicalization, which would otherwise refuse it as
        // "no host-and-path" -- correct for a git identity and the wrong answer for the one subject that
        // is not one (#2112).
        if (FleetMemory.IsFleet(value))
        {
            return FleetMemory.Slug;
        }

        if (RepositoryIdentity.TryCanonicalize(value) is not { Length: > 0 } canonical)
        {
            throw new CliArgumentException(
                $"'{value.Trim()}' is not a repository identity: it has no host-and-path to " +
                $"canonicalize, so no store file could be named for it. {usage}",
                "pass a canonical identity, for example 'github.com/owner/repo' — a clone URL " +
                "('https://github.com/owner/repo.git', 'git@github.com:owner/repo.git') is accepted " +
                "and normalised to one.");
        }

        MemoryImportOptionsParser.RequireAHostThatAProbeCouldAnswer(value, canonical, usage);
        return canonical;
    }

    private static string RequireValue(IReadOnlyList<string> args, int index)
    {
        if (index + 1 >= args.Count)
        {
            throw new CliArgumentException(
                $"Option '{args[index]}' requires a value. {Usage}",
                $"pass a value after '{args[index]}'.");
        }

        return args[index + 1];
    }
}
